export const NEXT_STEP = 'NEXT_STEP';
export const PREV_STEP = 'PREV_STEP';
export const UPDATE_USER = 'UPDATE_USER';
export const PROFILE = 'PROFILE';
export const PICTURE1 = 'PICTURE1';
export const PICTURE2 = 'PICTURE2';
export const PICTURE3 = 'PICTURE3';
export const REDIRECT = 'REDIRECT';
export const List = 'LIST';
;
